apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: palidrome-ps
spec:
  image: ghcr.io/kubewarden/policy-server:v0.2.1
  #replicas: 2
  replicas: 1
  serviceAccountName: policy-server
  env:
  - name: KUBEWARDEN_LOG_LEVEL
    value: debug
